language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - composer install -n --dev --no-progress

before_script:
  - 'cp -f app/config.php.dist app/config.php'

script:
  - vendor/bin/phpunit
